[watch]
watch = ["src"]
ignore = []

[serve]
address = "127.0.0.1"
port = 3000
open = false

[[hooks]]
stage = "build"
command = "tailwindcss"
command_arguments = ["-i", "input.css", "-o", "style/output.css"]
